package com.jpmac26.olddays;

import com.jpmac26.olddays.entities.enderman.RenderFactoryODEnderman;
import net.minecraftforge.fml.common.event.*;
import com.jpmac26.olddays.entities.EntityODEnderman;
import com.jpmac26.olddays.entities.enderman.RenderODEnderman;
import com.jpmac26.olddays.entities.EntityODSheep;
import com.jpmac26.olddays.client.gui.GuiHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.FMLClientHandler;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import static net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity;

import java.io.File;
import java.util.Arrays;

import net.minecraft.client.Minecraft;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.ResourceLocation;

/**
 * Created by James Pelster on 7/11/2016.
 */
@Mod(modid = "olddays", name = "Old Days Revisited", version = "0.1.1", acceptedMinecraftVersions = "1.10.2")
public class OldDaysRevisited
{
    @Mod.Instance("olddays")
    public static OldDaysRevisited olddays;
    public static final String MODID = "olddays";
    public static final String VERSION = "0.1.1";
    protected KeyHandler keyHandler;
    protected GuiHandler guiHandler;
    protected ODEventHandler eventHandler;
    
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        eventHandler = new ODEventHandler();
        MinecraftForge.EVENT_BUS.register(eventHandler);

		ModMetadata mMetadata = event.getModMetadata();
		mMetadata.credits = "CaptainSwag101, Kodehawa, Exalm";
		mMetadata.description = "Bringing back old Minecraft experiences.";
		mMetadata.autogenerated = false;
		mMetadata.version = VERSION;
		mMetadata.authorList = Arrays.asList(new String[] { "CaptainSwag101", "Kodehawa"});
		mMetadata.url = "https://www.github.com/jpmac26/OldDaysRevisited";
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event) {
        //register custom entities
        int id = 0;
        registerModEntity(EntityODEnderman.class, "Enderman", id++, this, 64, 3, true);
        registerModEntity(EntityODSheep.class, "Sheep", id++, this, 64, 3, true);

        clientInit(event);
    }

    @SideOnly(Side.CLIENT)
    public void clientInit(FMLInitializationEvent event) {
        registerRenderThings();

        guiHandler = new GuiHandler();
        NetworkRegistry.INSTANCE.registerGuiHandler(this, guiHandler);
        MinecraftForge.EVENT_BUS.register(guiHandler);

        keyHandler = new KeyHandler();
        MinecraftForge.EVENT_BUS.register(keyHandler);
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
		System.out.println("Old Days Revisited " + VERSION + " started successfully.");
    }

    @EventHandler
    public void loadWorldConfig(FMLServerStartingEvent event)
    {
        String configPath = event.getServer().getFolderName();
        if (event.getServer().isSinglePlayer())
            configPath = "saves/" + configPath;

        File configFile = new File(configPath, MODID + ".cfg");
        System.out.println("Loading config file for world: " + configFile.getPath());
        ConfigHandler.init(configFile);
    }

    @EventHandler
    public void saveWorldConfig(FMLServerStoppingEvent event)
    {
        ConfigHandler.syncConfig();
    }

    @SideOnly(Side.CLIENT)
    public void registerRenderThings()
    {
        RenderingRegistry.registerEntityRenderingHandler(EntityODEnderman.class, new RenderFactoryODEnderman());
    }
}
