package com.jpmac26.olddays;

import com.jpmac26.olddays.entity.EntityEndermanOld;
import com.jpmac26.olddays.entity.enderman.RenderEndermanFactoryOld;
import com.jpmac26.olddays.settings.ActionSettings;
import com.jpmac26.olddays.settings.GameplaySettings;
import com.jpmac26.olddays.settings.MobSettings;
import net.minecraft.entity.monster.EntityEnderman;
import net.minecraft.launchwrapper.Launch;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.event.*;
import com.jpmac26.olddays.entity.EntitySheepOld;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.relauncher.Side;

import static net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity;

import java.io.File;
import java.util.Arrays;

import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Created by James Pelster on 7/11/2016.
 */
@Mod(modid = "olddays", name = "Old Days Revisited", version = "0.2.0", acceptedMinecraftVersions = "1.11.2")
public class OldDaysRevisited
{
    @Mod.Instance
    public static OldDaysRevisited instance;
    public static final String MODID = "olddays";
    public static final String VERSION = "0.2.0";
    public static Logger LOGGER = LogManager.getLogger("OldDaysRevisited");
    public static boolean isSrg = !(boolean) Launch.blackboard.get("fml.deobfuscatedEnvironment");
    protected KeyHandler keyHandler;
    protected GuiHandler guiHandler;
    protected GameplaySettings.EventHandler gameplayEventHandler;
    protected MobSettings.EventHandler mobEventHandler;
    protected ActionSettings.EventHandler actionEventHandler;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        RenderingRegistry.registerEntityRenderingHandler(EntityEnderman.class, RenderEndermanFactoryOld.INSTANCE);


        // Register vanilla block replacements
        //Block.REGISTRY.register(Block.REGISTRY.getIDForObject(Blocks.FARMLAND), new ResourceLocation("farmland"), new BlockFarmlandOld());
        //Block.REGISTRY.register(Block.REGISTRY.getIDForObject(Blocks.FARMLAND), new ResourceLocation("farmland"), new BlockFarmlandOld());


        // Register event handlers for each category
        gameplayEventHandler = new GameplaySettings.EventHandler();
        MinecraftForge.EVENT_BUS.register(gameplayEventHandler);
        mobEventHandler = new MobSettings.EventHandler();
        MinecraftForge.EVENT_BUS.register(mobEventHandler);
        actionEventHandler = new ActionSettings.EventHandler();
        MinecraftForge.EVENT_BUS.register(actionEventHandler);

		ModMetadata mMetadata = event.getModMetadata();
		mMetadata.credits = "CaptainSwag101, Kodehawa, Exalm";
		mMetadata.description = "Bringing back old Minecraft experiences, one version at a time.";
		mMetadata.autogenerated = false;
		mMetadata.version = VERSION;
		mMetadata.authorList = Arrays.asList(new String[] { "CaptainSwag101", "Kodehawa" });
		mMetadata.url = "https://www.github.com/jpmac26/OldDaysRevisited";
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
        //register custom entity
        int id = 0;
        registerModEntity(new ResourceLocation("olddays:enderman"), EntityEndermanOld.class, "Enderman", id++, this, 64, 3, true);
        registerModEntity(new ResourceLocation("olddays:sheep"), EntitySheepOld.class, "Sheep", id++, this, 64, 3, true);
    }

    @SideOnly(Side.CLIENT)
    @EventHandler
    public void clientInit(FMLInitializationEvent event)
    {
        guiHandler = new GuiHandler();
        NetworkRegistry.INSTANCE.registerGuiHandler(this, guiHandler);
        MinecraftForge.EVENT_BUS.register(guiHandler);

        keyHandler = new KeyHandler();
        MinecraftForge.EVENT_BUS.register(keyHandler);
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
		LOGGER.info("OldDaysRevisited " + VERSION + " started successfully.");
    }

    @EventHandler
    public void getWorldConfig(FMLServerStartingEvent event)
    {
        String configPath = event.getServer().getFolderName();
        if (event.getServer().isSinglePlayer())
            configPath = "saves/" + configPath;

        File configFile = new File(configPath, MODID + ".cfg");
        if (configFile.exists())
            LOGGER.info("Loading config file for world at " + configFile.getPath());
        else
            LOGGER.info("Config file does not exist for this world, creating one at " + configFile.getPath());

        ConfigHandler.init(configFile);
    }

    @EventHandler
    public void saveWorldConfig(FMLServerStoppingEvent event)
    {
        LOGGER.info("Saving config file to " + ConfigHandler.config.getConfigFile().getPath());
        ConfigHandler.save();
    }
}
