package olddays;

import net.minecraftforge.fml.common.event.*;
import olddays.entities.enderman.EntityODEnderman;
import olddays.entities.enderman.RenderODEnderman;
import olddays.settings.ConfigManager;
import olddays.settings.EyecandySettings;
import olddays.client.gui.GuiHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.FMLClientHandler;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import static net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity;

import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraft.block.BlockStone;
import net.minecraft.block.BlockWorkbench;
import net.minecraft.block.SoundType;
import net.minecraft.client.Minecraft;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.SoundEvents;
import net.minecraft.util.ResourceLocation;

/**
 * Created by James Pelster on 7/11/2016.
 * Modified by: Kodehawa (7/22/2016)
 */
@Mod(modid = OldDaysRevisited.MODID, version = OldDaysRevisited.VERSION)
public class OldDaysRevisited
{
    public static final String MODID = "olddays";
    public static final String VERSION = "0.1";
    protected KeyHandler keyHandler;
	private EntityPlayer player = Minecraft.getMinecraft().thePlayer;
    protected GuiHandler guiHandler;
    private static final ResourceLocation oldcobbletest = new ResourceLocation("olddays:textures/blocks/olddays_chest_top.png");
    protected ODEventHandler eventHandler;
    @Mod.Instance("olddays")
    public static OldDaysRevisited olddays;
    
    
    
    @EventHandler
    public void preinit(FMLPreInitializationEvent event) {
        eventHandler = new ODEventHandler();
        MinecraftForge.EVENT_BUS.register(eventHandler);

		/***** OLD DAYS/NBX LITE METADATA DECLARATION START *****/
		
		ModMetadata mMetadata = event.getModMetadata();
		mMetadata.credits = "CaptainSwag101";
		mMetadata.description = "Bringing back old Minecraft experiences.";
		mMetadata.autogenerated = false;
		mMetadata.version = VERSION;
		mMetadata.authorList = Arrays.asList(new String[] { "CaptainSwag101"});
		mMetadata.url = "http://www.minecraftforum.net/topic/nope";
		
		/***** OLD DAYS/NBX LITE METADATA DECLARATION FINISH *****/
    	
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event) {
        //register custom stuff
        registerModEntity(EntityODEnderman.class, "Enderman", 0, this, 64, 1, true);

        clientInit(event);
    }

    @SideOnly(Side.CLIENT)
    public void clientInit(FMLInitializationEvent event) {
        registerRenderThings();

        guiHandler = new GuiHandler();
        NetworkRegistry.INSTANCE.registerGuiHandler(this, guiHandler);
        MinecraftForge.EVENT_BUS.register(guiHandler);

        keyHandler = new KeyHandler();
        MinecraftForge.EVENT_BUS.register(keyHandler);
    }

    @EventHandler
    public void postLoad(FMLPostInitializationEvent event)
    {
        new ConfigManager();
		System.out.println("Old Days" + VERSION + "succefully started in" + Minecraft.getMinecraft().getVersion());

    }
    
    @EventHandler
	public void serverStarting(FMLServerStartingEvent ev)
	{
    	
	}

    @SideOnly(Side.CLIENT)
    public void registerRenderThings()
    {
        RenderingRegistry.registerEntityRenderingHandler(EntityODEnderman.class, new RenderODEnderman(FMLClientHandler.instance().getClient().getRenderManager()));
    }
}
